### ISSUE TITLE
Local Resources Page

### ISSUE THREAD

**Issue by NaveenP94** [junior-design-156/gt-excel-website#11]
As a user I want to navigate to a page where I can find local resources

- [ ] Map with local resources #8 

- [ ] Local Transportation Information #9 

- [ ] text for about this page #10
