### ISSUE TITLE
Jobs Page

### ISSUE THREAD

**Issue by NaveenP94** [junior-design-156/gt-excel-website#18]
This will be the tab for the page where users can search for different job search websites, and will also have the flow chart to make this info easier to read. 

- [x] Clickable Flow chart #15 

- [x] Textbox with external links #16 

- [x] About job search page info #17
